#!/usr/bin/env bash
echo "===> Creating bucket $1"


if [ -z "$1" ]; then
  echo "There needs to be a bucket name eg ./bucket <name>"
  exit 1
fi



aws s3api create-bucket \
--bucket $1 \
--create-bucket-configuration="LocationConstraint=ap-south-1" \
--query Location \
--output text